---
deployment:
  tasks:
    # Set deployment path for frontend only (MISEDA INSPECT SRL hosting)
    - export DEPLOYPATH=/home/aduadu321/public_html/
    
    # Build frontend application
    - npm run build
    
    # Deploy frontend files to public_html
    - /bin/cp -R dist/* $DEPLOYPATH
    
    # Set proper permissions for web files
    - chmod -R 755 $DEPLOYPATH
    
    # Create simple PHP backend for contact forms (optional)
    - echo "<?php header('Content-Type: application/json'); echo json_encode(['message' => 'ITP NOTIFICATION - MISEDA INSPECT SRL', 'status' => 'active']); ?>" > $DEPLOYPATH/api.php
    
    - echo "Frontend deployment completed for ITP NOTIFICATION - MISEDA INSPECT SRL"