---
deployment:
  tasks:
    # Set deployment paths for MISEDA INSPECT SRL hosting
    - export DEPLOYPATH=/home/aduadu321/public_html/
    - export APPPATH=/home/aduadu321/itp-notification/
    
    # Create necessary directories
    - mkdir -p $APPPATH
    - mkdir -p $DEPLOYPATH
    
    # Build and create deployment packages
    - npm run build:all
    - npm run zip:build
    
    # Deploy from build archive
    - cd /home/aduadu321 && unzip -o build-package.zip
    - /bin/cp -R build/backend/* $APPPATH
    - /bin/cp -R build/frontend/* $DEPLOYPATH
    - /bin/cp package.json $APPPATH
    - /bin/cp database/schema.sql $APPPATH
    
    # Install production dependencies for backend
    - cd $APPPATH && npm ci --omit=dev
    
    # Clean up build files
    - rm -f /home/aduadu321/build-package.zip
    - rm -rf /home/aduadu321/build
    
    # Set proper permissions
    - chmod -R 755 $DEPLOYPATH
    - chmod -R 755 $APPPATH
    
    # Restart Node.js application (if supported by hosting)
    - echo "Deployment completed for ITP NOTIFICATION - MISEDA INSPECT SRL"